CREATE TABLE IF NOT EXISTS visitor_count (
  id    INTEGER PRIMARY KEY CHECK (id = 1),
  count INTEGER NOT NULL DEFAULT 0
);

INSERT INTO visitor_count (id, count) VALUES (1, 0) ON CONFLICT(id) DO NOTHING;
